export const rodizios = {
    "RODIZIO CLIPS PARA DESLIZANTE": 0.3,
    "RODIZIO DESLIZANTE MINI NORMAL": 0.3,
    "RODIZIO DESLIZANTE MAX REDONDO": 0.3,
    "RODIZIO DESLIZANTE MAX NORMAL": 0.3,
    "RODIZIO DESLIZANTE FITA SMART": 0.42,
    "RODIZIO DESLIZANTE ADAPTADOR FITA": 0.42,
    "RODIZIO DESLIZANTE FITA FACIL": 0.4
}