export const trilhos = {
    "TRILHO MINI SIMPLES ": 11.9,
    "TRILHO MINI DUPLO": 27.2,
    "TRILHO MINI TRIPLO ": 35.9,
    "TRILHO MINI FLEXIVEL": 19,
    "REGUA P/FLEXIVEL (PECA COM 3MTS)": 34,
    "TRILHO MAX SIMPLES COM ABA": 15,
    "TRILHO MAX SIMPLES SEM ABA": 12.2,
    "TRILHO MAX ALTO ": 19.4,
    "TRILHO MAX DUPLO": 23,
    "TRILHO MAX DUPLO ALONGADO ": 38.8,
    "TRILHO MAX TRIPLO": 39.9,
    "TRILHO MAX DUPLO BANDO": 37.9
}