export const tubos = {
    "TUBO DESLIZANTE 19MM CROMADO/BRANCO/ IMBUIA/PRETO": 23.5,
    "TUBO DESLIZANTE 19MM OURO VELHO /AÇO ESCOVADO": 27.2,
    "TUBO DESLIZANTE 28MM CROMADO/BRANCO/IMBUIA/PRETO": 39.9,
    "TUBO DESLIZANTE 28MM OURO VELHO /AÇO ESCOVADO": 43.8,
    "TUBO BALI BRANCO": 31.8,
    "TUBO BALI  AÇO ESCOVADO": 33.9,
    "TUBO BALI CROMADO ANODIZADO ": 45.6,
    "TUBO 19MM CROMADO POLIDO / BRANCO / PRETO": 17.8,
    "TUBO 19MM OURO VELHO /AÇO ESCOVADO/CROMADO C/VERNIZ": 19.4,
    "TUBO 28MM CROMADO POLIDO / BRANCO / PRETO": 27.2,
    "TUBO 28MM OURO VELHO /AÇO ESCOVADO/CROMADO C/VERNIZ": 29.4,
}